Repository draw-dev/DRAW, pull requests merged in 2018-03, with the labels that each got.

#36 Convenience methods and housekeeping
  .gitignore
  lib/draw.dart
  lib/src/listing/mixins/base.dart
  lib/src/models/comment_forest.dart
  lib/src/models/comment_impl.dart
  lib/src/models/inbox.dart
  lib/src/models/message.dart
  lib/src/models/mixins/inboxable.dart
  lib/src/models/mixins/inboxtoggleable.dart
  lib/src/models/mixins/voteable.dart
  lib/src/models/redditor.dart
  lib/src/models/submission_impl.dart
  lib/src/models/subreddit.dart
  lib/src/models/user_content.dart
  lib/src/objector.dart
  lib/src/reddit.dart
  lib/src/user.dart
  lib/src/util.dart
  test/comment/comment_test.dart
  test/inbox/inbox_tests.dart
  test/redditor/redditor_test.dart
  test/submission/submission_test.dart
  test/subreddit/subreddit_test.dart
  test/user/user_test.dart
  test/user_content/user_content_test.dart
Labels: enhancement, refactor, testing

#39 Added IOS and Android as supported OS's.
  lib/src/config_file_reader.dart
Labels: bug-fix, flutter

#45 Subreddit Moderation Functionality
  lib/draw.dart
  lib/src/getter_utils.dart
  lib/src/models/comment_impl.dart
  lib/src/models/message.dart
  lib/src/models/mixins/user_content_mixin.dart
  lib/src/models/submission_impl.dart
  lib/src/models/subreddit.dart
  lib/src/models/subreddit_moderation.dart
  lib/src/objector.dart
  lib/src/reddit.dart
  test/subreddit/subreddit_mod_queue.json
  test/subreddit/subreddit_mod_reports.json
  test/subreddit/subreddit_mod_spam.json
  test/subreddit/subreddit_mod_unmoderated.json
  test/subreddit/subreddit_moderation_edited.json
  test/subreddit/subreddit_moderation_inbox.json
  test/subreddit/subreddit_moderation_log.json
  test/subreddit/subreddit_moderation_settings.json
  test/subreddit/subreddit_moderation_test.dart
  test/subreddit/subreddit_moderation_unread.json
  test/subreddit/subreddit_update_settings.json
  test/test_authenticator.dart
  test/test_utils.dart
Labels: enhancement
