Repository draw-dev/DRAW, pull requests merged in 2018-09, with the labels that each got.

#101 0.4.0 Release
  .travis.yml
  CHANGELOG.md
  lib/src/models/submission_impl.dart
  lib/src/models/subreddit.dart
  pubspec.yaml
  tool/travis.sh
Labels: release

#103 [0.4.1] Update pubspec to reference forks of package:color and package:ini
  pubspec.yaml
Labels: dart-2, project health, release

#105 Subreddit Flair implementation
  lib/draw.dart
  lib/src/api_paths.dart
  lib/src/listing/listing_generator.dart
  lib/src/models/flair.dart
  lib/src/models/subreddit.dart
  lib/src/objector.dart
  test/subreddit/lib_subreddit_flair_call.json
  test/subreddit/lib_subreddit_flair_configure.json
  test/subreddit/lib_subreddit_flair_delete.json
  test/subreddit/lib_subreddit_flair_delete_all.json
  test/subreddit/lib_subreddit_flair_link_templates.json
  test/subreddit/lib_subreddit_flair_redditor_templates.json
  test/subreddit/lib_subreddit_flair_set_flair.json
  test/subreddit/lib_subreddit_flair_update.json
  test/subreddit/subreddit_test.dart
  test/test_authenticator.dart
Labels: enhancement

#107 Misc pubspec and analysis fixes
  lib/src/models/comment_forest.dart
  lib/src/models/comment_impl.dart
  lib/src/models/multireddit.dart
  lib/src/models/submission_impl.dart
  lib/src/objector.dart
  pubspec.yaml
Labels: dart-2, project health

#108 Submission flair implementation
  lib/draw.dart
  lib/src/models/submission_impl.dart
  test/submission/lib_submission_flair.json
  test/submission/submission_test.dart
Labels: enhancement

#109 Prep for 0.4.2 release
  CHANGELOG.md
  pubspec.yaml
Labels: release

#110 Added nsfw/spoiler parameters to submit
  lib/src/models/subreddit.dart
Labels: enhancement

#111 Merge "Added nsfw/spoiler parameters to submit (#110)" with updated tests
  lib/src/models/subreddit.dart
  test/subreddit/lib_subreddit_submit.json
  test/user_content/lib_user_content_editable.json
  test/user_content/lib_user_content_replyable.json
  test/user_content/lib_user_content_reportable.json
  test/user_content/lib_user_content_saveable.json
  test/user_content/lib_user_content_toggleable.json
Labels: enhancement, testing

#113 Propagate errors correctly for static Reddit create methods
  lib/src/reddit.dart
Labels: bug-fix
